# This file instructs Cloud Build on how to build and push the Docker image.
steps:
  # 1. Use the dockercloud builder to build the image [cite: 14]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      # Tag the image with the Artifact Registry path and the commit SHA [cite: 15]
      'us-central1-docker.pkg.dev/mdkaif-474201/kaif-101001476/assignment2:${SHORT_SHA}', 
      '.'
    ]

  # 2. Push the Docker image to your Artifact Registry [cite: 16]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/mdkaif-474201/kaif-101001476/assignment2:${SHORT_SHA}'
    ]

# List the images that are created by this build
images:
  - 'us-central1-docker.pkg.dev/mdkaif-474201/kaif-101001476/assignment2:${SHORT_SHA}''

# Set the logging option [cite: 17, 18]
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
